#pragma once

enum class ITEM_TYPE
{
	ITEM_TYPE_RECOVERY,
	ITEM_TYPE_BALL,
	ITEM_TYPE_IMPORTANT,
	ITEM_TYPE_SKIL_MACHINE,
	ITEM_TPYE_EQUIPABLE
};

enum class POCKETMON_ATTIBUTE
{
	POCKETMON_ATTIBUTE_FIRE,
	POCKETMON_ATTIBUTE_STONE,
	POCKETMON_ATTIBUTE_WATER,
	POCKETMON_ATTIBUTE_GRASS
};